import type { Metadata } from "next";
import { Poppins, Bebas_Neue } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400", "700"],
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bebas",
  weight: "400",
});

const gotham = localFont({
  src: [
    { path: "./fonts/Gotham-Font/Gotham-Black.otf", weight: "700" },
    { path: "./fonts/Gotham-Font/GothamBook.ttf", weight: "400" },
  ],
  display: "swap",
  variable: "--font-gotham",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${poppins.variable} ${gotham.variable} ${bebas.variable} antialiased vsc-initialized flex min-h-screen min-w-full flex-col justify-between bg-white font-body text-semiblack`}
      >
        {children}
      </body>
    </html>
  );
}
